apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sonakube
spec:
  selector:
    matchLabels:
      app: sonakube
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: sonakube
    spec:
      containers:
        - name: manikube
          image: manikube:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003 # The port that the container is running on in the cluster